import type { Metadata } from 'next'
import { GoogleOAuthProvider } from '@react-oauth/google';
// These styles apply to every route in the application
import '../public/assest/cssFile/globals.css'
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body><GoogleOAuthProvider clientId="986706595817-k8m2oik51jbesdhclgs264hbqkrhkkc9.apps.googleusercontent.com">{children}</GoogleOAuthProvider></body>
    </html>
    
  )
}